build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/Annotation.java, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/Comment.java, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/enumeration/AnnotationType.java, src/main/java/uk/gov/hmcts/reform/em/annotation/repository/AnnotationRepository.java, src/main/java/uk/gov/hmcts/reform/em/annotation/repository/CommentRepository.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/AnnotationService.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/CommentService.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/dto/AnnotationDTO.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/dto/CommentDTO.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/dto/RectangleDTO.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/AnnotationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/CommentServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/mapper/AnnotationMapper.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/mapper/CommentMapper.java, src/main/resources/db/changelog/20180917100757_added_entity_Annotation.xml, src/main/resources/db/changelog/20180917100758_added_entity_Comment.xml, src/main/resources/db/changelog/20180917101255_added_entity_Rectangle.xml, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResourceIntTest.java
=> Em 732 integrate annotation viewer with api

dependency-check-suppressions.xml
=> Suppress app insights dependency failure.

src/main/java/uk/gov/hmcts/reform/em/annotation/config/SwaggerConfiguration.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/FilterAnnotationSet.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResource.java
Added swagger doc lines above each of the APIs endpoints. Edited swagger configuration to search for swagger doc information within the correct directory.
```
[ ] Yes
[x] No
```
=> Swagger docs annotations api

src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/FilterAnnotationSet.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResource.java
Remove deprecated swaggerdocs description tag
```
[ ] Yes
[x] No
```
=> Remove deprecated swaggerdocs description tag

Dockerfile, Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, gradle/wrapper/gradle-wrapper.properties, infrastructure/application-insights.tf, infrastructure/main.tf, infrastructure/variables.tf, kubernetes/config.aat.yaml, kubernetes/config.saat.yaml, kubernetes/deployment.template.yaml, src/aat/java/uk/gov/hmcts/reform/em/annotation/testutil/Env.java
Embed AKS into the pipeline
```
[ ] Yes
[ ] No
```
=> building AKS to pipeline

docker-compose-dependencies.yml, src/aat/java/uk/gov/hmcts/reform/em/annotation/testutil/TestUtil.java
=> IDAM fixes

infrastructure/aat.tfvars
=> [PREVIEW] changing base url to sidam

charts/em-anno/Chart.yaml, charts/em-anno/requirements.yaml, charts/em-anno/values.aat.template.yaml, charts/em-anno/values.preview.template.yaml, charts/em-anno/values.yaml
apply bugfix changes
```
[ ] Yes
[ ] No
```
=> templating and alias

Jenkinsfile_CNP, dependency-check-suppressions.xml
stops the Jenkins build before it reaches prod
```
[ ] Yes
[ ] No
```
=> stop building to prod

build.gradle
bump pg :fist_right: :fist_left: 
```
[ ] Yes
[x] No
```
=> bump-pg-version

Dockerfile, build.gradle, docker-compose-dependencies.yml, lib/AI-Agent.xml, web.config
https://tools.hmcts.net/jira/browse/EM-2028
Updated idam URL and added in AppInsights related lines
=> Update Java image

charts/em-anno/Chart.yaml, infrastructure/main.tf, infrastructure/output.tf
https://tools.hmcts.net/jira/browse/EM-2032
Fix deprecation issues and use component for vault
=> Fix deprecation issues and use component for vault

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/EM-2032
Reverted the vault key changes
=> Reverted the vault key changes

infrastructure/main.tf
Replaced the deprecated vault_uri attribute with key_vault_id attribute
=> Replaced the vault_uri with key_vault_id

infrastructure/main.tf
Updated the vault name attribute for postgres details
=> Updated the vault name attribute for postgres details

Jenkinsfile_CNP, build.gradle, charts/em-anno/Chart.yaml, charts/em-anno/values.preview.template.yaml, charts/em-anno/values.yaml, dependency-check-suppressions.xml, infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf, src/main/resources/bootstrap.yaml
=> EM-2110: Configure annotation api for migration to aks

infrastructure/main.tf
=> EM-2110: Rename local_key_vault to key_vault

charts/em-anno/values.aat.template.yaml, charts/em-anno/values.yaml
=> EM-2110: remove db values

infrastructure/main.tf
=> EM-2110: Rename var for azurem key vault

charts/em-anno/Chart.yaml, charts/em-anno/values.aat.template.yaml, charts/em-anno/values.yaml, src/main/resources/bootstrap.yaml
=> EM-2110: Add DB values to the values.aat template

charts/em-anno/Chart.yaml, charts/em-anno/values.yaml
=> EM:2110: Add db values

charts/em-anno/values.aat.template.yaml
=> EM-2110: Add jdbc to the url for the db

src/main/resources/bootstrap.yaml
=> EM-2110: fix naming issue

infrastructure/main.tf
fix annotation-api deployment
```
[ ] Yes
[X] No
```
=> move resource group to top of the config

Jenkinsfile_CNP, charts/em-anno/values.aat.template.yaml, charts/em-anno/values.preview.template.yaml, dependency-check-suppressions.xml
Added in disableLegacyDeployment()
=> Added in disableLegacyDeployment()

Jenkinsfile_CNP
Updated disableLegacyDeploymentOnAAT()
=> Updated disableLegacyDeploymentOnAAT()

Jenkinsfile_CNP
=> Disabling Legacy deployment on AAT

src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/EM-2205
```
[ ] Yes
[ ] No
```
=> changing the appinsights var in bootstrap for flux.

dependency-check-suppressions.xml
=> Suppressed vulnerability

infrastructure/main.tf
=> disable ASE

charts/em-anno/Chart.yaml, charts/em-anno/requirements.yaml, charts/em-anno/values.aat.template.yaml, charts/em-anno/values.preview.template.yaml, charts/em-anno/values.yaml
https://tools.hmcts.net/jira/browse/EM-2255
=> Removed alias related lines

src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslator.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslatorIntTest.java
https://tools.hmcts.net/jira/browse/EM-2235
reduce error response verbosity to meet ITHC requirements
```
[ ] Yes
[X] No
```
=> reduce error response verbosity to meet ITHC requirements

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/EM-2280
add xui to s2s whitelist
```
[ ] Yes
[X] No
```
=> add xui to s2s whitelist

charts/em-anno/Chart.yaml, charts/em-anno/values.aat.template.yaml, charts/em-anno/values.yaml
https://tools.hmcts.net/jira/browse/EM-2298
=> Updated the respective URL's

charts/em-anno/Chart.yaml, charts/em-anno/values.preview.template.yaml
=> Indentpgres

Jenkinsfile_CNP, charts/em-anno/values.preview.template.yaml, dependency-check-suppressions.xml
=> Remove dockerbuild

infrastructure/main.tf
=> remove ase code

charts/em-anno/Chart.yaml, charts/em-anno/requirements.yaml
=> update Java chart

dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/AbstractAuditingEntity.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/ResponseUtil.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResourceIntTest.java
- this will remove the large number of errors clogging up the app insights
```
[ ] Yes
[ ] No
```
=> Remove 404 error from api call to get annotation sets

README.md, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/TestSecurityConfiguration.java
Added in TestSecConfig and updated readme
=> Added in TestSecConfig and updated readme

Jenkinsfile_CNP, charts/em-anno/Chart.yaml, charts/em-anno/values.preview.template.yaml, charts/em-anno/values.yaml, src/main/java/uk/gov/hmcts/reform/em/annotation/config/security/SecurityConfiguration.java
=> Removed issuer validation

src/main/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/EmptyResponseException.java
=> EM-2687: Return 204 for bookmarks and 404 for filter of annotation sets

infrastructure/demo.tfvars
=> update demo man ID

Jenkinsfile_CNP, Jenkinsfile_parameterized, build.gradle, dependency-check-suppressions.xml, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/AnnotationScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/OpenIdConnectScenarios.java
feature/EM-2722  Added SerenityIntegrationSpringRunner in Functional Tests.
=> feature/EM-2722 Added SerenityIntegrationSpringRunner in Functional Tests.

Jenkinsfile_CNP, build.gradle, dependency-check-suppressions.xml, pacts/annotation_api-idam_api.json, src/contractTest/java/uk/gov/hmcts/reform/em/annotation/IdamConsumerTest.java
https://tools.hmcts.net/jira/browse/EM-2881
Integrating pact to run in build pipeline and publish pacts on Pact broker
```
[ ] Yes
[ X ] No
```
=> Em 2881 integrate pact pipeline

build.gradle, dependency-check-suppressions.xml
EM-2721-Fix for SerenitySinglePageReporting
=> EM-2721-Fix for SerenitySinglePageReporting

build.gradle, pacts/annotation_api-idam_api.json, src/contractTest/java/uk/gov/hmcts/reform/em/annotation/IdamConsumerTest.java
https://tools.hmcts.net/jira/browse/EM-2881
Fix for POST request body generation in pact json
```
[ ] Yes
[ X ] No
```
=> EM-2881 request body generation in pact json

Jenkinsfile_CNP, dependency-check-suppressions.xml
=> remove in chts

Jenkinsfile_CNP, build.gradle, dependency-check-suppressions.xml, src/aat/resources/application.yml, src/main/java/uk/gov/hmcts/reform/em/annotation/config/security/JwtGrantedAuthoritiesConverter.java, src/main/java/uk/gov/hmcts/reform/em/annotation/config/security/SecurityUtils.java, src/main/java/uk/gov/hmcts/reform/em/annotation/repository/IdamRepository.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/IdamDetailsFilterService.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/IdamDetailsFilterServiceImpl.java, src/test/java/uk/gov/hmcts/reform/em/annotation/repository/IdamRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/service/impl/IdamDetailsFilterServiceImplIntTest.java
Updated em-test-helper version and changed the userdetails endpoint to userinfo endpoint
=> Em 2979 user endpoint change

pacts/annotation_api-idam_api.json, src/contractTest/java/uk/gov/hmcts/reform/em/annotation/IdamConsumerTest.java
Added changes related to State in Pact tests
```
[ ] Yes
[ X ] No
```
=> EM-2881 Pact state related changes

build.gradle, src/contractTest/java/uk/gov/hmcts/reform/em/annotation/IdamConsumerTest.java
Updated username and added in the task for pact
=> Updated username

src/contractTest/java/uk/gov/hmcts/reform/em/annotation/IdamConsumerTest.java
=> Updated client details

src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/AnnotationSetScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/BookmarkScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/TagScenarios.java
=> EM-2924: Add functional test cases for tags and bookmarks

Jenkinsfile_CNP, build.gradle
=> Updated pact contract

Jenkinsfile_nightly, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/EM-3097
=> Updated nightly build file

Jenkinsfile_CNP, Jenkinsfile_nightly, build.gradle
EM-3015:EM-Anno-Mutation Tests Nightly Build
=> EM-3015:EM-Anno-Mutation Tests Nightly Build

.gitignore, bin/start-local-environment.sh, build.gradle, docker-compose-dependencies.yml, src/aat/java/uk/gov/hmcts/reform/em/annotation/smoke/SmokeTest.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/WelcomeResource.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/WelcomeResourceTest.java
https://tools.hmcts.net/jira/browse/EM-3118
=> Updated em-test-helper version

infrastructure/main.tf
=> updated MI details

build.gradle, charts/em-anno/Chart.yaml, charts/em-anno/requirements.yaml, charts/em-anno/values.preview.template.yaml, charts/em-anno/values.yaml, dependency-check-suppressions.xml, gradle.properties, gradle/wrapper/gradle-wrapper.properties, src/main/java/uk/gov/hmcts/reform/em/annotation/config/security/SecurityConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/TagResourceIntTest.java
https://tools.hmcts.net/jira/browse/EM-3089
=> Updated spring boot and java chart version

build.gradle, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/AnnotationScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/AnnotationSetScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/BookmarkScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/MetadataScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/OpenIdConnectScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/TagScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/smoke/SmokeTest.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/testutil/TestUtil.java
=> EM-3207 Implemented

audit.json
=> EM-3240- Anno API : Suppress nightly build security issues

infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/prod.tfvars
Removed mi value for env tf files
=> Removed mi value for env tf files

audit.json
=> EM-3255- Anno API : Suppress nightly build security issues

build.gradle, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/AnnotationScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/AnnotationSetScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/BookmarkScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/MetadataScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/OpenIdConnectScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/TagScenarios.java
=> EM-3259 - Anno API : Add retry logic for failing functional test cases

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/EM-3273
=> Resolved vulnerability

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/EM-3289
=> Resolved vulnerabilities

audit.json
=> EM-3324 - EM-Anno api: suppress security scan error

audit.json
=> EM-3325 - EM-Anno api: suppress security scan error

build.gradle, dependency-check-suppressions.xml
=> Em 3361 resolved vulnerability

build.gradle
=> EM-3426 - EM-Anno api: Upgrade serenity version

src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/CommentScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/testutil/TestUtil.java
=> EM-3462 - EM-Anno api: Add functional test cases for CommentsResource

src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/CommentScenarios.java
=> EM-3462_2 - fix for jenkins build failures

src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/CommentScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/RectangleScenarios.java
=> EM-3473 - EM-Anno api: Add functional test cases for RectangleResource

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/EM-3520
=> Resolved CVE-2021-21290

audit.json
=> EM-3524 - EM-Anno api: suppress security scan error

build.gradle, dependency-check-suppressions.xml
=> Em 3507 - Updated build.gradle and resolved CVEs

src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/AnnotationScenarios.java
=> EM-3514 - EM-Anno api: Add functional test cases for AnnotationResource

src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/BookmarkScenarios.java
=> EM-3489 - Add functional test cases for BookmarkResource

src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/MetadataScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/testutil/TestUtil.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/testutil/ToggleProperties.java
=> EM-3550 - EM-Anno api: Add functional test cases for MetaDataResource

src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/AnnotationScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/AnnotationSetScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/BookmarkScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/CommentScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/RectangleScenarios.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResource.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResourceIntTest.java
https://tools.hmcts.net/jira/browse/EM-3471
https://tools.hmcts.net/jira/browse/EM-3500
https://tools.hmcts.net/jira/browse/EM-3482
https://tools.hmcts.net/jira/browse/EM-3540
https://tools.hmcts.net/jira/browse/EM-3549
```
[ ] Yes
[X] No
```
=> Corrected API delete response codes

audit.json
=> EM-3631 - EM-Anno api: suppress security scan error

src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/FilterAnnotationSetScenarios.java
=> EM-3644 - EM-Anno api: Add functional test cases for FilterAnnotationSet

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/EM-3678
Fixed CVE-2020-15824, CVE-2020-29582
```
[ ] Yes
[X] No
```
=> Fixed CVE-2020-15824, CVE-2020-29582

src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/BookmarkScenarios.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResource.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResourceIntTest.java
https://tools.hmcts.net/jira/browse/EM-3497
Fixed Get Bookmarks by DocumentId response coder
```
[ ] Yes
[X] No
```
=> Fix Get Bookmarks by DocumentId response code

charts/em-anno/Chart.yaml
N/A
updated java chart version
```
[ ] Yes
[X] No
```
=> updated java chart version

build.gradle
https://tools.hmcts.net/jira/browse/EM-3739
Update checkstyle settings to generate report for main and tests
```
[ ] Yes
[X] No
```
=> EM-Anno api: Update checkstyle settings to generate report for main and tests

src/main/java/uk/gov/hmcts/reform/em/annotation/info/BuildInfo.java
https://tools.hmcts.net/jira/browse/EM-3754
Fixed Resource Leak
```
[ ] Yes
[X] No
```
=> Fixed Resource Leak

src/main/java/uk/gov/hmcts/reform/em/annotation/info/BuildInfo.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/FilterAnnotationSet.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/TagResource.java
https://tools.hmcts.net/jira/browse/EM-3754
Fixed Resource Leak issues
```
[ ] Yes
[X] No
```
=> Fixed Resource Leak issues

src/main/java/uk/gov/hmcts/reform/em/annotation/info/BuildInfo.java
https://tools.hmcts.net/jira/browse/EM-3754
Fixed Resource Leak issue
```
[ ] Yes
[X] No
```
=> Fixed Resource Leak issue

src/main/java/uk/gov/hmcts/reform/em/annotation/config/Constants.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/MetaDataResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResource.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/MetaDataResourceTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResourceTest.java
https://tools.hmcts.net/jira/browse/EM-3754
Fixed Mass Assignment: Insecure Binder Configuration issue
```
[ ] Yes
[X] No
```
=> Fixed Mass Assignment: Insecure Binder Configuration issue

src/main/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/util/StringUtilities.java, src/test/java/uk/gov/hmcts/reform/em/annotation/service/impl/util/StringUtilitiesTest.java
https://tools.hmcts.net/jira/browse/EM-3866
Fixed Header manipulation bug
```
[ ] Yes
[X] No
```
=> Fixed Header manipulation bug

src/main/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResource.java, src/test/java/uk/gov/hmcts/reform/em/annotation/service/impl/util/StringUtilitiesTest.java
https://tools.hmcts.net/jira/browse/EM-3870
Resolved Null dereference bug
```
[ ] Yes
[X] No
```
=> Resolved Null dereference bug

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/EM-3921
Updated DB details to resolve access issue
```
[ ] Yes
[X] No
```
=> Updated DB details

Jenkinsfile_nightly, build.gradle, config/fortify-client.properties, src/main/resources/logback-spring.xml, src/test/resources/logback.xml
https://tools.hmcts.net/jira/browse/EM-3959
Added in files for FortifyScan in nightly build
```
[ ] Yes
[X] No
```
=> Added in files for FortifyScan in nightly build

build.gradle, src/main/java/uk/gov/hmcts/reform/em/annotation/Application.java, src/main/java/uk/gov/hmcts/reform/em/annotation/config/security/EmSecurityConfiguration.java, src/main/java/uk/gov/hmcts/reform/em/annotation/config/security/SecurityUtils.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/ServiceNameAspect.java, src/test/java/uk/gov/hmcts/reform/em/annotation/service/ServiceNameAspectTest.java
https://tools.hmcts.net/jira/browse/EM-3972
Added in logging to capture consuming service name
```
[ ] Yes
[X] No
```
=> Added in logging to capture consuming service name

charts/em-anno/Chart.yaml
https://tools.hmcts.net/jira/browse/EM-3994
Updated Chart Java version
```
[ ] Yes
[X] No
```
=> Updated Chart Java version

infrastructure/state.tf
EM-4024
fix terraform provider issue
```
[ ] Yes
[x] No
```
=> EM-4024: fix terraform provider issue

src/main/java/uk/gov/hmcts/reform/em/annotation/config/audit/EntityAuditEventListener.java, src/main/java/uk/gov/hmcts/reform/em/annotation/config/security/SecurityUtils.java, src/main/java/uk/gov/hmcts/reform/em/annotation/config/security/SpringSecurityAuditorAware.java, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/AbstractAuditingEntity.java, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/EntityAuditEvent.java, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/PersistentAuditEvent.java, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/Rectangle.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/FilterAnnotationSet.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/dto/CommentDTO.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/AnnotationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/AnnotationSetServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/MetadataServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/mapper/AnnotationMapper.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/mapper/BookmarkMapper.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/mapper/EntityMapper.java
EM-4044
fix checkstyle type error - only Error few type dealt
```
[ ] Yes
[x] No
```
=> EM-4044: fix checkstyle type error

src/main/java/uk/gov/hmcts/reform/em/annotation/authchecker/EmAuthCheckerUserDetailsService.java, src/main/java/uk/gov/hmcts/reform/em/annotation/authchecker/EmServiceAndUserDetails.java, src/main/java/uk/gov/hmcts/reform/em/annotation/config/SwaggerConfiguration.java, src/main/java/uk/gov/hmcts/reform/em/annotation/config/audit/AsyncEntityAuditEventWriter.java, src/main/java/uk/gov/hmcts/reform/em/annotation/config/audit/AuditEventConverter.java, src/main/java/uk/gov/hmcts/reform/em/annotation/config/audit/EntityAuditAction.java, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/AbstractAuditingEntity.java, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/Annotation.java, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/AnnotationSet.java, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/EntityAuditEvent.java, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/TagId.java, src/main/java/uk/gov/hmcts/reform/em/annotation/repository/CustomAuditEventRepository.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/mapper/EntityMapper.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/util/StringUtilities.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/TestUtil.java
EM-4044
fix checkstyle type error v2
```
[ ] Yes
[x] No
```
=> EM-4044: fix checkstyle type error v2

build.gradle
EM-4044
fix sonar exclusion
```
[ ] Yes
[x] No
```
=> EM-4044: fix sonar exclusion

src/main/java/uk/gov/hmcts/reform/em/annotation/authchecker/EmServiceAndUserDetails.java, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/AnnotationSet.java, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/Comment.java, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/EntityAuditEvent.java, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/Rectangle.java, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/TagId.java, src/main/java/uk/gov/hmcts/reform/em/annotation/repository/EntityAuditEventRepository.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/MetaDataResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/CustomParameterizedException.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/BookmarkService.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/TagService.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/dto/AnnotationDTO.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/dto/AnnotationSetDTO.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/dto/CommentDTO.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/dto/RectangleDTO.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/BookmarkServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/TagServiceImpl.java
EM-4044
fix checkstyle type error v4
```
[ ] Yes
[x] No
```
=> EM-4044: fix checkstyle type error v4

src/main/java/uk/gov/hmcts/reform/em/annotation/rest/util/HeaderUtil.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResourceTest.java
EM-4044
fix sonar major code smell
```
[ ] Yes
[x] No
```
=> EM-4044: fix sonar major code smell

infrastructure/main.tf, infrastructure/variables.tf
postgres upgrade v11
postgres upgrade v11
```
[ ] Yes
[ x] No
```
=> EM 3457 postgres upgrade v11

infrastructure/state.tf
EM-4064
fix terraform azurerm version 2.79.1
```
[ ] Yes
[x] No
```
=> EM-4064 fix terraform azurerm version 2.79.1

src/main/java/uk/gov/hmcts/reform/em/annotation/service/ServiceNameAspect.java, src/test/java/uk/gov/hmcts/reform/em/annotation/service/ServiceNameAspectTest.java
https://tools.hmcts.net/jira/browse/EM-4065
Resolve Error status with code : 500 for ServiceNameAspect
```
[ ] Yes
[X] No
```
=> Add InvalidTokenException to ServiceNameAspect and its test class

audit.json
security.sh fix
```
[ ] Yes
[ ] No
```
=> security-scan-em-anno

charts/em-anno/Chart.yaml, charts/em-anno/values.yaml, infrastructure/main.tf
https://tools.hmcts.net/jira/browse/EM-3457
Pointing to v11 DB details.
Swapping of secrets is required for DB migration step in the master build pipeline.
```
[ ] Yes
[X] No
```
=> Pointing to v11 DB details

Jenkinsfile_CNP, Jenkinsfile_nightly, build.gradle, docker-compose-dependencies-simulator.yml, docker-compose-dependencies.yml, src/aat/resources/application.yml, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslator.java
EM-4073
remove jcenter reference
```
[ ] Yes
[x] No
```
=> EM-4073: remove jcenter reference

build.gradle
https://tools.hmcts.net/jira/browse/EM-4113
Resolve CVE-2021-22044
```
[ ] Yes
[X] No
```
=> Fix CVE-2021-22044

build.gradle, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/Bookmark.java, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/Rectangle.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/dto/BookmarkDTO.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/dto/RectangleDTO.java
https://tools.hmcts.net/jira/browse/EM-3719
Resolved checkstyle errors
```
[ ] Yes
[X] No
```
=> Resolved checkstyle errors

src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/BadRequestAlertException.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/CustomParameterizedException.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/EmailAlreadyUsedException.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/EmailNotFoundException.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/InternalServerErrorException.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/InvalidPasswordException.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/LoginAlreadyUsedException.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/ServiceNameAspect.java
https://tools.hmcts.net/jira/browse/EM-4208
Fix SonarQube issues
```
[ ] Yes
[X] No
```
=> Fix sonar issues

Dockerfile, build.gradle
https://tools.hmcts.net/jira/browse/EM-4224
Reverted Java 17 version to fix failing mutation tests
```
[ ] Yes
[X] No
```
=> Reverted Java 17 version

charts/em-anno/Chart.yaml
https://tools.hmcts.net/jira/browse/EM-4268
Update helm chart
```
[ ] Yes
[X] No
```
=> Update helm chart

audit.json
1.  Em Annotation API Security Scan fix
```
[ ] Yes
[ x] No
```
=> [EM-4287]-Security Scan Fix

charts/em-anno/Chart.yaml
bump java chart
```
[ ] Yes
[X] No
```
=> bump java chart

bin/start-local-environment.sh, docker-compose-dependencies.yml, src/aat/resources/application.yml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/EM-4291
Resolved local setup port issue
```
[ ] Yes
[X] No
```
=> Resolved local setup port issue

security.sh
security fix -swagger url changed to v3
```
[ ] Yes
[x] No
```
=> security fix -swagger url changed to v3

build.gradle
Added jackson-bom to be set to 2.13.1
```
[ ] Yes
[ ] No
```
=> added: jackson-databind version to manually be set to 2.13.2.1.

audit.json
Annotation API Security Scan Fix
```
[ ] Yes
[x ] No
```
=> [EM-4356]-SecurityScan Fix

build.gradle, src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/BookmarkServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/MetadataServiceImpl.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/service/impl/MetadataServiceImplTest.java
https://tools.hmcts.net/jira/browse/EM-3579
Resolved sonar issue - java:S5804
```
[ ] Yes
[X] No
```
=> Resolved sonar issue - java:S5804

src/main/java/uk/gov/hmcts/reform/em/annotation/config/SwaggerConfiguration.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/FilterAnnotationSet.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/MetaDataResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/TagResource.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/EM-4397
Updated Swagger doc
```
[ ] Yes
[X] No
```
=> Updated Swagger doc

audit.json
https://tools.hmcts.net/jira/browse/EM-4410
Fix security scan by adding ignore
```
[ ] Yes
[x] No
```
=> Add ignore for 10054 bookmarks_PUT

src/main/resources/db/changelog/00000000000000_initial_schema.xml
https://tools.hmcts.net/jira/browse/EM-4418
Updated column size for principal
```
[ ] Yes
[X] No
```
=> Updated column size for principal

src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/AnnotationService.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/AnnotationServiceImpl.java
https://tools.hmcts.net/jira/browse/EM-4443
Added in more logs and try-catch to investigate the issue.
```
[ ] Yes
[X] No
```
=> Added in more logs and try-catch

src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResource.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResource.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResourceIntTest.java
https://tools.hmcts.net/jira/browse/EM-4443
Resolved Sonar issue
```
[ ] Yes
[X] No
```
=> Resolved Sonar issue

src/main/java/uk/gov/hmcts/reform/em/annotation/rest/FilterAnnotationSet.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/FilterAnnotationSetTest.java
https://tools.hmcts.net/jira/browse/EM-4450
Added in try catch to handle a scenario
```
[ ] Yes
[X] No
```
=> Added in try catch to handle a scenario

src/main/java/uk/gov/hmcts/reform/em/annotation/config/security/SecurityUtils.java, src/test/java/uk/gov/hmcts/reform/em/annotation/config/security/SecurityUtilsTest.java
https://tools.hmcts.net/jira/browse/EM-3592
Add unit tests for SecurityUtils
```
[ ] Yes
[x] No
```
=> Em 3592 code coverage securityutils

src/test/java/uk/gov/hmcts/reform/em/annotation/config/audit/EntityAuditEventListenerTest.java
https://tools.hmcts.net/jira/browse/EM-3593
Add unit tests for EntityAuditEventListener
```
[ ] Yes
[x] No
```
=> Em 3593 code coverage entityauditeventlistener

README.md, build.gradle, docker-compose-dependencies-db.yml, settings.gradle, src/aat/resources/application.yml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/EM-4470
Add cftlib
```
[ ] Yes
[x] No
```
=> Add cftlib

bin/idam/idam.sh, bin/start-local-environment.sh, docker-compose-dependencies-simulator.yml, docker-compose-dependencies.yml
https://tools.hmcts.net/jira/browse/EM-4470
Updated local S2S port and Idam port
```
[ ] Yes
[X] No
```
=> Updated local S2S port and Idam port

src/test/java/uk/gov/hmcts/reform/em/annotation/repository/CustomAuditEventRepositoryIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/FilterAnnotationSetTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResourceTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/TagResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslatorIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/service/impl/IdamDetailsFilterServiceImplIntTest.java
https://tools.hmcts.net/jira/browse/EM-4473
Resolved integration test failures
```
[ ] Yes
[X] No
```
=> Resolved integration test failures

audit.json, config/owasp/dependency-check-suppressions.xml
=> added suppression for single fingerprint for em anno

audit.json
AnnotationAPI Security Scan fix
```
[ ] Yes
[ x] No
```
=> [EM-4494]-AnnotationAPI Security Scan fix

build.gradle, config/owasp/dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/EM-4515
Removed redundant cve suppression
```
[ ] Yes
[X] No
```
=> Removed redundant cve suppression

infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/EM-2233
Updated DB core to 4 for Demo env
```
[ ] Yes
[X] No
```
=> Updated DB core to 4 for Demo env

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/EM-2233
Disable syncBranchesWithMaster till DB core is upgraded on all lower environments.
```
[ ] Yes
[X] No
```
=> Disable syncBranchesWithMaster till DB core is upgraded

infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/EM-2233
Updated DB core from 2 to 4.
```
[ ] Yes
[X] No
```
=> Updated DB core from 2 to 4

src/main/resources/db/migration/V1__baseline_migration.sql
https://tools.hmcts.net/jira/browse/EM-4344
Set type of metadata id to bigint
```
[ ] Yes
[x] No
```
=> Fix metadata id attribute

src/main/java/uk/gov/hmcts/reform/em/annotation/service/ServiceNameAspect.java
https://tools.hmcts.net/jira/browse/EM-4560
Resolved service exception
```
[ ] Yes
[X] No
```
=> Resolved service exception

charts/em-anno/Chart.yaml, charts/em-anno/values.preview.template.yaml, charts/em-anno/values.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/EM-4532
Resolve preview secret issue
```
[ ] Yes
[x] No
```
=> Resolve preview secret issue

.github/dependabot.yml, .github/renovate.json, .github/stale.yml, renovate.json
https://tools.hmcts.net/jira/browse/EM-4567
Added in dependabot config
```
[ ] Yes
[X] No
```
=> Added in dependabot config

charts/em-anno/Chart.yaml, charts/em-anno/values.yaml, infrastructure/main.tf
EM-4227 copy app-insight connection from rpa
=> EM-4227 copy app-insight connection from rpa

build.gradle
Merge pull request #949 from hmcts/dependabot/gradle/org.flywaydb-flyway-core-9.3.0
=> revert "Merge pull request #949 from hmcts/dependabot/gradle/org.flywaydb-flyway-core-9.3.0"

src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/BookmarkScenarios.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ErrorConstants.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslator.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslatorIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslatorTestController.java
Fix the response codes of errors that were showing 500
```
[ ] Yes
[x] No
```
=> Fix response codes

src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ErrorConstants.java
https://tools.hmcts.net/jira/browse/EM-3992
Hide problem base url
```
[ ] Yes
[x] No
```
=> Hide problem base url

src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslator.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslatorIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslatorTestController.java
handle psql exception
```
[ ] Yes
[x] No
```
=> handle psql exception

build.gradle, config/owasp/dependency-check-suppressions.xml
=> EM-4645-avoid-CVE-2022-42003

src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ErrorConstants.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslator.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslatorIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslatorTestController.java
handle constraint violation exception
```
[ ] Yes
[x] No
```
=> handle constraint violation exception

src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslator.java
log psql error message
```
[ ] Yes
[x] No
```
=> log psql error message

src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/CommentScenarios.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResource.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResourceIntTest.java
https://tools.hmcts.net/jira/browse/EM-3472
Respond with 400 for comment with no annotation id
```
[ ] Yes
[x] No
```
=> Respond with 400 for comment with no annotation id

audit.json
=> EM-4667 - added single fingerprint to audit.json to fix em anno pipeline

build.gradle, src/main/java/uk/gov/hmcts/reform/em/annotation/config/security/SecurityConfiguration.java, src/test/java/uk/gov/hmcts/reform/em/annotation/config/security/SecurityConfigurationTest.java
https://tools.hmcts.net/jira/browse/EM-3594
Add unit test for SecurityConfiguration
```
[ ] Yes
[x] No
```
=> Add unit test for SecurityConfiguration

audit.json
=> EM-4714 - added single fingerprint to audit.json to fix em anno pipeline

README.md, build.gradle, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResourceIntTest.java, src/test/resources/config/application.yaml
https://tools.hmcts.net/jira/browse/EM-4706
Use postgres test db
```
[ ] Yes
[x] No
```
=> Use postgres test db

src/main/java/uk/gov/hmcts/reform/em/annotation/rest/EmErrorController.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/ErrorControllerImpl.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/EmErrorControllerIntTest.java
Enable exception handling for errors in authentication
```
[ ] Yes
[x] No
```
=> Enable exception handling for errors in authentication

src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/BookmarkScenarios.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResource.java
https://tools.hmcts.net/jira/browse/EM-4479
Returning all bookmarks
```
[ ] Yes
[ x] No
```
=> EM-4479: Returning all bookmarks

audit.json
https://tools.hmcts.net/jira/browse/EM-4942
EM-4942 - added 1 fingerprint to audit.json to fix em anno pipeline
=> EM-4942 - added 1 fingerprint to audit.json to fix em anno pipeline

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized
=> EM-5019 fix pipeline

charts/em-anno/Chart.yaml, charts/em-anno/values.preview.template.yaml, charts/em-anno/values.yaml
https://tools.hmcts.net/jira/browse/EM-5182
Updated Preview dependency chart to create and consume ExUI and Idam on Preview. Rest of the dependencies are pointing to AAT.
```
[ ] Yes
[X] No
```
=> Preview dependency chart update

src/aat/java/uk/gov/hmcts/reform/em/annotation/smoke/SmokeTest.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/WelcomeResource.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/WelcomeResourceTest.java
[https://tools.hmcts.net/jira/browse/EM-5193](url)
Welcome endpoint to return JSON response
```
[ ] Yes
[x] No
```
=> Welcome Endpoint to return Json format

audit.json
=> EM-5198 suppress sec vul

charts/em-anno/Chart.yaml, charts/em-anno/values.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/EM-5405
Updated Hikari connection-timeout & Removed redundant tomcat attributes.
```
[ ] Yes
[X] No
```
=> Updated Hikari connection-timeout

src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/BookmarkScenarios.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResource.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResourceIntTest.java
https://tools.hmcts.net/jira/browse/EM-5415
respond with 204 when no bookmarks
```
[ ] Yes
[x] No
```
=> respond with 204

audit.json
https://tools.hmcts.net/jira/browse/EM-5435
added 4 fingerprints to audit.json
=> em-5435: added 4 fingerprints to audit.json

audit.json
https://tools.hmcts.net/jira/browse/EM-5483
added 1 fingerprint to audit.json
=> em-5483: added 1 fingerprint to audit.json

audit.json
https://tools.hmcts.net/jira/browse/EM-5519
added 1 fingerprint to audit.json
=> em-5519: added 1 fingerprint to audit.json

.github/renovate.json
EM-5551 fix renovate config
it needs to extend HMCTS renovate
=> EM-5551 fix renovate config

config/owasp/dependency-check-suppressions.xml
EM-5569  dependency-check-suppressions.xml
=> EM-5569  dependency-check-suppressions.xml

lib/applicationinsights.json
EM-5505 reduce app-insight logs
=> EM-5505 reduce app-insight logs

infrastructure/main.tf, infrastructure/perftest.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/EM-5526
Added in v15 DB details for perftest
=> Added in v15 DB details for perftest

Dockerfile
EM-5649 fix app-insight logging
=> EM-5649 fix app-insight logging

src/main/java/uk/gov/hmcts/reform/em/annotation/config/audit/AsyncEntityAuditEventWriter.java, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/EntityAuditEvent.java, src/main/resources/db/migration/V2__jhi_entity_audit_event_entity_value2_migrated.sql
https://tools.hmcts.net/jira/browse/EM-5665
add new columns to EntityAuditEvent for copying entity values
=> add new columns to EntityAuditEvent

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/EM-5526
Removed v15 DB details. We will recreate the v15 DB after the current activity to resolve large object issue is completed.
=> Removed v15 DB details.

audit.json
https://tools.hmcts.net/jira/browse/EM-5710
added 1 fingerprint to audit.json
=> em-5710: added 1 fingerprint to audit.json

build.gradle
EM-5717 arrange dependency management
=> EM-5717 arrange dependency management

infrastructure/main.tf, infrastructure/perftest.tfvars, infrastructure/prod.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/EM-5626
Removed v11 DB related config.
=> Removed v11 DB related config

charts/em-anno/Chart.yaml, charts/em-anno/values.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/EM-5742
Removed redundant service names from s2s whitelist.
=> Removed redundant service names from s2s whitelist

src/main/java/uk/gov/hmcts/reform/em/annotation/config/security/SecurityConfiguration.java
https://tools.hmcts.net/jira/browse/EM-5805
update deprecated security config
=> update deprecated config

src/main/java/uk/gov/hmcts/reform/em/annotation/config/ExceptionHandlingAsyncTaskExecutor.java, src/main/java/uk/gov/hmcts/reform/em/annotation/rest/EmErrorController.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/AnnotationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/BookmarkServiceImpl.java
https://tools.hmcts.net/jira/browse/EM-5922
Fixed code smells, suppressed a single throwable smell as it needs to remain generic to pick up and rethrow errors from outside the controller.
=> fixed code smells

charts/em-anno/Chart.yaml
https://tools.hmcts.net/jira/browse/EM-5953
=> Upgrading java chart to 5.2.0

charts/em-anno/Chart.yaml, charts/em-anno/values.yaml
https://tools.hmcts.net/jira/browse/EM-5974
=> Enabling spot instances for lower envs

charts/em-anno/Chart.yaml, charts/em-anno/values.yaml
https://tools.hmcts.net/jira/browse/EM-5989
Disabled Spot instances.
=> Disabled Spot instances

src/main/java/uk/gov/hmcts/reform/em/annotation/config/audit/AsyncEntityAuditEventWriter.java
https://tools.hmcts.net/jira/browse/EM-6066
Resolve private field access issue.
=> Resolve private field access issue

src/main/java/uk/gov/hmcts/reform/em/annotation/config/audit/AsyncEntityAuditEventWriter.java, src/main/java/uk/gov/hmcts/reform/em/annotation/config/audit/EntityAuditEventListener.java, src/main/java/uk/gov/hmcts/reform/em/annotation/domain/AbstractAuditingEntity.java, src/test/java/uk/gov/hmcts/reform/em/annotation/config/audit/EntityAuditEventListenerTest.java
https://tools.hmcts.net/jira/browse/EM-6070
remove code smell
=> remove suppressed code smell

README.md, build.gradle, src/aat/resources/application.yml
https://tools.hmcts.net/jira/browse/EM-6251
local setup
=> local setup

src/aat/java/uk/gov/hmcts/reform/em/annotation/config/ContainerImageNameSubstitutor.java, src/aat/resources/testcontainers.properties, src/test/java/uk/gov/hmcts/reform/em/annotation/config/ContainerImageNameSubstitutor.java, src/test/resources/testcontainers.properties
[Em -6333 ](https://tools.hmcts.net/jira/browse/EM-6333)change test container
=> Em-6333 change test container

Jenkinsfile_CNP, build.gradle, src/contractTest/java/uk/gov/hmcts/reform/em/annotation/IdamConsumerTest.java
https://tools.hmcts.net/jira/browse/EM-6327
Em 6327 update pact to 4.6.15
=> Em 6327 update pact

src/test/java/uk/gov/hmcts/reform/em/annotation/BaseTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/repository/CustomAuditEventRepositoryIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/EmErrorControllerIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/FilterAnnotationSetTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/TagResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslatorIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/service/impl/IdamDetailsFilterServiceImplIntTest.java
https://tools.hmcts.net/jira/browse/EM-6342
migrate tests to junit 5
=> migrate tests to junit 5

build.gradle
https://tools.hmcts.net/jira/browse/EM-6342
Add junit5 plugin for pitest
=> Em 6342 pitest junit5

charts/em-anno/Chart.yaml
https://tools.hmcts.net/jira/browse/EM-6544
Upgrading to oci charts, bumping chart minor version
- [
=> EM-6544 Upgrading to oci chart

Jenkinsfile_CNP, build.gradle, docker-pactbroker-compose.yml, src/contractTest/java/uk/gov/hmcts/reform/em/annotation/ContractTestConfiguration.java, src/contractTest/java/uk/gov/hmcts/reform/em/annotation/PostAnnotationsConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/em/annotation/PostAnnotationsProviderTest.java
https://tools.hmcts.net/jira/browse/EM-6449
Em 6449 add pact test
=> Em 6449 add pact test

src/contractTest/java/uk/gov/hmcts/reform/em/annotation/consumer/AnnotationsConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/em/annotation/provider/AnnotationsProviderTest.java
https://tools.hmcts.net/jira/browse/EM-6452
add pact delete test for annotation
=> EM-6452 add pact delete test for annotation

src/contractTest/java/uk/gov/hmcts/reform/em/annotation/consumer/AnnotationSetConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/em/annotation/provider/AnnotationSetProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/em/annotation/provider/BaseProviderTest.java
https://tools.hmcts.net/jira/browse/EM-6454
add pact test for put annotation set
=> add pact test

config/owasp/dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/EM-6653
Removed redundant CVE suppressions
N/A
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
=> Removed redundant CVE suppressions

src/test/resources/config/application.yaml
https://tools.hmcts.net/jira/browse/EM-6691
add config for test container
=> add config

build.gradle
=> check property

charts/em-anno/Chart.yaml, charts/em-anno/values.preview.template.yaml, charts/em-anno/values.yaml
https://tools.hmcts.net/jira/browse/EM-6484
set metadata endpoint toggle to true, matching the value in flux and preview
=> Enable toggle

src/contractTest/java/uk/gov/hmcts/reform/em/annotation/consumer/FilterAnnotationSetConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/em/annotation/provider/BaseProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/em/annotation/provider/FilterAnnotationSetProviderTest.java
https://tools.hmcts.net/jira/browse/EM-6483
add pact tests
=> add pact tests

src/test/java/uk/gov/hmcts/reform/em/annotation/config/audit/AsyncEntityAuditEventWriterTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResourceIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslatorIntTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslatorTestController.java, src/test/java/uk/gov/hmcts/reform/em/annotation/service/impl/AnnotationServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/service/impl/AnnotationSetServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/em/annotation/service/impl/BookmarkServiceImplTest.java
https://tools.hmcts.net/jira/browse/EM-6613
Added and updated unit tests
Will be completed before merging this PR.
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
=> Added and updated unit tests
